In [1]:
import numpy as np

## Vector to vector multiplication

In [2]:
arr=np.array([2,3,4,6])
arr

array([2, 3, 4, 6])

In [3]:
arr2=np.array([1,0,1,2])
arr2

array([1, 0, 1, 2])

In [4]:
def vector_to_vector_multiplication(arr1,arr2):
    assert arr1.shape[0]==arr2.shape[0], "number of columns are not matching(rows in math term)"

    n=arr.shape[0]
    result= 0
    for i in range(n):
        result += arr1[i]*arr2[i]
    return result

res = vector_to_vector_multiplication(arr,arr2)
res

np.int64(18)

In [5]:
arr.dot(arr2)

np.int64(18)

In [6]:
arr3=np.array([2,4,6,8,10])
arr3

array([ 2,  4,  6,  8, 10])

In [7]:
vector_to_vector_multiplication(arr,arr3)

AssertionError: number of columns are not matching(rows in math term)

## Matrix to vector multiplication

In [ ]:
u=np.array([[10,20,30,40],
           [5,7,9,1],
           [3,4,3,2]])
u

array([[10, 20, 30, 40],
       [ 5,  7,  9,  1],
       [ 3,  4,  3,  2]])

In [ ]:
def matrix_vector_multi(arr1,arr2):
    print(arr1.shape[1],arr2.shape[0])
    assert arr1.shape[1]==arr2.shape[0], "number of columns are not matching(rows in math term)"
    n=arr1.shape[0]
    result=np.zeros(n)
    for i in range(n):
        result[i]=vector_to_vector_multiplication(arr1[i],arr2)
    return result

matrix_vector_multi(u,arr)

4 4


array([440.,  73.,  42.])

In [ ]:
u.dot(arr)

array([440,  73,  42])

## Matrix to Matrix multiplication

In [11]:
v=np.array([[1,2,3],
           [5,6,7],
           [9,10,11],
           [12,13,14]])
v

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
def matrix_matrix_multi(mat1,mat2):
    assert mat1.shape[1]==mat2.shape[0], "number of columns are not matching(rows in math term)"

    n=mat1.shape[0]
    m=mat1.shape[1]
    result=np.zeros((n,m))
    for ind in range(n):
        result[:,ind]=matrix_vector_multi(mat1,mat2[:,ind])
    return result

matrix_matrix_multi(u,v)

4 4
4 4
4 4


array([[ 860.,  960., 1060.,    0.],
       [ 133.,  155.,  177.,    0.],
       [  74.,   86.,   98.,    0.]])

In [ ]:
u.dot(v)

array([[ 860,  960, 1060],
       [ 133,  155,  177],
       [  74,   86,   98]])

In [ ]:
v.dot(u)

array([[ 29,  46,  57,  48],
       [101, 170, 225, 220],
       [173, 294, 393, 392],
       [227, 387, 519, 521]])

## Identity matrix

In [9]:
I=np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
v2= v[[0,1,2]]
v2

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [13]:
v.dot(I)

array([[ 1.,  2.,  3.],
       [ 5.,  6.,  7.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

In [15]:
I.dot(v2)

array([[ 1.,  2.,  3.],
       [ 5.,  6.,  7.],
       [ 9., 10., 11.]])

## Inverse

In [14]:
v2_inv = np.linalg.inv(I)
v2_inv

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
v2_inv.dot(v2)

array([[ 1.,  2.,  3.],
       [ 5.,  6.,  7.],
       [ 9., 10., 11.]])