In [2]:
import numpy as np

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(3,5.2)

array([5.2, 5.2, 5.2])

In [6]:
arr=np.array([3,4,5,6,7])
arr

array([3, 4, 5, 6, 7])

In [7]:
arr[2]

np.int64(5)

In [8]:
arr[1]=100
arr[1]

np.int64(100)

In [9]:
arr

array([  3, 100,   5,   6,   7])

In [10]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [11]:
np.linspace(10,50,6)

array([10., 18., 26., 34., 42., 50.])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
arr2 =np.array([[2,3,4],[6,7,8],[9,10,11],[22,33,44]])

In [14]:
arr2[1,2]

np.int64(8)

In [15]:
arr2[2,2]=283
arr2

array([[  2,   3,   4],
       [  6,   7,   8],
       [  9,  10, 283],
       [ 22,  33,  44]])

In [16]:
arr2[2]

array([  9,  10, 283])

In [17]:
arr2[:,1]

array([ 3,  7, 10, 33])

In [18]:
np.random.rand(3,2,5)

array([[[0.11177185, 0.54090476, 0.84408858, 0.75025637, 0.82750634],
        [0.563494  , 0.6957307 , 0.24011829, 0.48382188, 0.38215943]],

       [[0.84478882, 0.48582626, 0.8615819 , 0.24865057, 0.05416163],
        [0.0010347 , 0.36270725, 0.47999435, 0.83918719, 0.2145258 ]],

       [[0.09920221, 0.51771881, 0.2551964 , 0.54014373, 0.88956656],
        [0.56999989, 0.48546153, 0.70411369, 0.26907122, 0.22231351]]])

In [19]:
np.random.seed(2)
10*np.random.rand(3,2)

array([[4.35994902, 0.25926232],
       [5.49662478, 4.35322393],
       [4.20367802, 3.30334821]])

In [20]:
np.random.randn(3,2)

array([[ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761],
       [ 0.55145404,  2.29220801]])

In [21]:
np.random.randint(2,44,(4,2))

array([[ 5, 40],
       [ 6, 41],
       [40, 35],
       [ 5,  7]], dtype=int32)

In [22]:
a=np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [23]:
a*2

array([0, 2, 4, 6, 8])

In [24]:
a+5

array([5, 6, 7, 8, 9])

In [25]:
a/5

array([0. , 0.2, 0.4, 0.6, 0.8])

In [26]:
a-10

array([-10,  -9,  -8,  -7,  -6])

In [27]:
2-a

array([ 2,  1,  0, -1, -2])

In [28]:
b= (10*(a/22))+100
b

array([100.        , 100.45454545, 100.90909091, 101.36363636,
       101.81818182])

In [29]:
a+b

array([100.        , 101.45454545, 102.90909091, 104.36363636,
       105.81818182])

In [30]:
a[2]=150

In [31]:
a>b

array([False, False,  True, False, False])

In [32]:
a>2

array([False, False,  True,  True,  True])

In [33]:
a[a>b]

array([150])

In [34]:
a[b>a]

array([0, 1, 3, 4])

In [35]:
b[b>a]

array([100.        , 100.45454545, 101.36363636, 101.81818182])

In [36]:
b[a>b]

array([100.90909091])

In [37]:
b.min()

np.float64(100.0)

In [38]:
b.max()

np.float64(101.81818181818181)

In [39]:
a.sum()

np.int64(158)

In [40]:
a.mean()

np.float64(31.6)

In [41]:
a.std()

np.float64(59.21688948264676)

In [ ]:
a

array([  0,   1, 150,   3,   4])

In [48]:
a.shape[0]

5

In [50]:
arr

array([  3, 100,   5,   6,   7])